"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ

from config.logging import InterceptHandler, setup_logger

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Initialize loguru
setup_logger()

# Initialize django-environ
env = environ.Env()

# Load .env from project root
_env_path = BASE_DIR.parent / ".env"
if _env_path.exists():
    env.read_env(_env_path)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS", default=[])


# Application definition

INSTALLED_APPS = [
    "daphne",  # ASGI server for WebSocket and SSE support - must be first
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",  # https://whitenoise.readthedocs.io/en/latest/
    "django.contrib.staticfiles",
    "django.contrib.sites",
    # Third party apps
    "django_eventstream",  # Server-Sent Events
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "tailwind",
    "django_htmx",
    "crispy_forms",
    "crispy_tailwind",
    "ordered_model",
    "django_celery_results",
    "markdownx",
    "django_browser_reload",
    "django_cotton.apps.SimpleAppConfig",
    "template_partials.apps.SimpleAppConfig",
    # Local apps
    "apps.common",
    "apps.accounts",
    "apps.ai",
    "apps.stories",
    "apps.landing",
    "apps.dashboard",
    "apps.subscriptions",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "allauth.account.middleware.AccountMiddleware",
]

if DEBUG:
    # Add django_browser_reload middleware only in DEBUG mode
    MIDDLEWARE += [
        "django_browser_reload.middleware.BrowserReloadMiddleware",
    ]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates", BASE_DIR / "apps/ai/prompt_templates"],
        "APP_DIRS": False,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "loaders": [
                (
                    "template_partials.loader.Loader",
                    [
                        (
                            "django.template.loaders.cached.Loader",
                            [
                                "django_cotton.cotton_loader.Loader",
                                "django.template.loaders.filesystem.Loader",
                                "django.template.loaders.app_directories.Loader",
                            ],
                        )
                    ],
                )
            ],
            "builtins": [
                "django_cotton.templatetags.cotton",
                "template_partials.templatetags.partials",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration with PostgreSQL support via environment variables
if env("DB_NAME", default=None):
    # Use PostgreSQL if database environment variables are provided
    DATABASES = {
        "default": {
            "ENGINE": env("DB_ENGINE", default="django.db.backends.postgresql"),
            "NAME": env("DB_NAME"),
            "USER": env("DB_USER"),
            "PASSWORD": env("DB_PASSWORD"),
            "HOST": env("DB_HOST", default="localhost"),
            "PORT": env("DB_PORT", default="5432"),
        }
    }
else:
    # Fallback to SQLite for development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR.parent / "var" / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files (User uploaded content)
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR.parent / "var" / "media"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Tailwind configuration
TAILWIND_APP_NAME = "theme"

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

# Django Allauth configuration
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = env.int("SITE_ID", default=1)
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_EMAIL_VERIFICATION = env("ACCOUNT_EMAIL_VERIFICATION", default="mandatory")
ACCOUNT_UNIQUE_EMAIL = True

# Email configuration (env-driven; rely on Django defaults if unset)
EMAIL_BACKEND = env("EMAIL_BACKEND", default=None)  # None -> Django default
EMAIL_HOST = env("EMAIL_HOST", default=None)
EMAIL_PORT = env.int("EMAIL_PORT", default=None)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=False)
EMAIL_HOST_USER = env("EMAIL_HOST_USER", default=None)
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default=None)

# Login/Logout URLs
LOGIN_REDIRECT_URL = "/dashboard"
LOGOUT_REDIRECT_URL = "/"
LOGIN_URL = "account_login"

# Stripe settings (env-only; no defaults)
STRIPE_PUBLIC_KEY = env("STRIPE_PUBLIC_KEY", default=None)
STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY", default=None)
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET", default=None)
STRIPE_PRICE_ID = env("STRIPE_PRICE_ID", default=None)

# AI settings (env-only; no defaults)
OPENAI_API_KEY = env("OPENAI_API_KEY", default=None)

# Celery settings (env-only; remove conflicting defaults)
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default=None)
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default=None)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# EventStream configuration for Server-Sent Events
EVENTSTREAM_STORAGE_CLASS = "django_eventstream.storage.DjangoModelStorage"
EVENTSTREAM_CHANNELMANAGER_CLASS = "apps.common.sse.ChannelManager"

# EventStream Redis configuration (only if provided)
_event_redis_url = env("EVENTSTREAM_REDIS_URL", default=None) or env("REDIS_URL", default=None)
if _event_redis_url:
    EVENTSTREAM_REDIS = {"url": _event_redis_url}
else:
    _host = env("REDIS_HOST", default=None)
    if _host:
        EVENTSTREAM_REDIS = {
            "host": _host,
            "port": env.int("REDIS_PORT", default=6379),
            "db": env.int("REDIS_DB", default=0),
        }
    # else: don't define EVENTSTREAM_REDIS in base


LOGGING = {
    "version": 1,
    # IMPORTANT: drop Django's built-in handlers so you don't get duplicates
    "disable_existing_loggers": True,
    "handlers": {
        "loguru": {"()": InterceptHandler},  # your InterceptHandler
    },
    # Single sink: everything bubbles to root -> InterceptHandler -> Loguru
    "root": {"handlers": ["loguru"], "level": "INFO"},
    "loggers": {
        # Let these bubble up to root; DO NOT attach their own handlers
        "django": {"level": "INFO", "propagate": True},
        "django.server": {"level": "WARNING", "propagate": True},  # or INFO if you want access logs
        "django.request": {"level": "INFO", "propagate": True},
        "daphne": {"level": "INFO", "propagate": True},
        "daphne.server": {"level": "INFO", "propagate": True},
        "daphne.http_protocol": {"level": "INFO", "propagate": True},
        # If you see asyncio duplicates/noise:
        "asyncio": {"level": "WARNING", "propagate": True},
    },
}
