# Generated by Django 5.2.4 on 2025-09-10 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0010_conversation_run"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="run",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="run",
            name="first_ts",
        ),
        migrations.RemoveField(
            model_name="run",
            name="last_ts",
        ),
        migrations.RemoveField(
            model_name="run",
            name="status",
        ),
        migrations.CreateModel(
            name="Artifacts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="artifacts", to="ai.run"
                    ),
                ),
            ],
        ),
    ]
