[keymap]
preset = "default"
destructive_delete = true

[keymap.overrides]

[diagnostics]

[completion]
activate_on_typing = true
copilot = false

[formatting]
line_length = 120

[runtime]
reactive_tests = true
auto_instantiate = false
std_stream_max_bytes = 1000000
watcher_on_save = "lazy"
output_max_bytes = 8000000
auto_reload = "autorun"
on_cell_change = "lazy"
default_sql_output = "auto"
default_auto_download = []

[snippets]
custom_paths = []
include_default_snippets = true

[experimental]

[package_management]
manager = "uv"

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = true

[ai]
rules = ""
mode = "manual"

[ai.models]
custom_models = []
displayed_models = []

[display]
default_table_page_size = 10
theme = "light"
reference_highlighting = false
default_table_max_columns = 50
cell_output = "above"
default_width = "medium"
dataframes = "rich"
code_editor_font_size = 14

[language_servers.pylsp]
enable_ruff = true
enabled = false
enable_mypy = true
enable_pylint = false
enable_flake8 = false
enable_pyflakes = false
enable_pydocstyle = false

[language_servers.basedpyright]

[language_servers.ty]

[server]
browser = "default"
follow_symlink = false
