[save]
format_on_save = true
autosave = "after_delay"
autosave_delay = 1000

[keymap]
destructive_delete = true
preset = "default"

[keymap.overrides]

[language_servers.pylsp]
enabled = false
enable_flake8 = false
enable_pylint = false
enable_mypy = true
enable_pydocstyle = false
enable_ruff = true
enable_pyflakes = false

[language_servers.ty]

[language_servers.basedpyright]

[diagnostics]

[experimental]

[server]
follow_symlink = false
browser = "default"

[runtime]
auto_reload = "autorun"
default_auto_download = []
auto_instantiate = true
std_stream_max_bytes = 1000000
on_cell_change = "lazy"
default_sql_output = "auto"
reactive_tests = true
watcher_on_save = "lazy"
output_max_bytes = 8000000

[formatting]
line_length = 120

[snippets]
custom_paths = []
include_default_snippets = true

[display]
dataframes = "rich"
cell_output = "above"
code_editor_font_size = 14
reference_highlighting = false
theme = "light"
default_table_page_size = 10
default_table_max_columns = 50
default_width = "medium"

[completion]
copilot = false
activate_on_typing = true

[ai]
mode = "manual"
rules = ""

[ai.models]
displayed_models = []
custom_models = []

[package_management]
manager = "uv"
