repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version
    rev: 0.8.17
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.9
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format