[project]
name = "story-sprout"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "celery>=5.5.3",
    "crispy-tailwind>=1.0.3",
    "django>=5.2.4",
    "django-allauth>=65.10.0",
    "django-browser-reload>=1.18.0",
    "django-celery-results>=2.6.0",
    "django-cotton>=2.1.3",
    "django-crispy-forms>=2.4",
    "django-htmx>=1.23.2",
    "django-markdownx>=4.0.9",
    "django-ninja>=1.4.3",
    "django-ordered-model>=3.7.4",
    "django-render-block>=0.11",
    "django-tailwind>=4.2.0",
    "django-template-partials>=25.1",
    "flower>=2.0.1",
    "gunicorn>=23.0.0",
    "litellm>=1.74.3",
    "pillow>=11.3.0",
    "python-dotenv>=1.1.1",
    "redis>=6.2.0",
    "stripe>=12.3.0",
    "whitenoise>=6.9.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.3.0",
    "ruff>=0.12.9",
]

[tool.ruff]
# Set the maximum line length to 119 characters
line-length = 119

# Enable auto-fixing for all fixable rules
fix = true

# Select default linting rules
lint.select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "I",   # isort
]

# Configure docstring and comment line length
lint.pydocstyle.convention = "google"

[tool.ruff.format]
# Use double quotes for strings
quote-style = "double"

# Prefer single-line magic trailing comma
skip-magic-trailing-comma = false

# Set docstring line length to 79 characters
docstring-code-line-length = 79
