[project]
name = "story-sprout-suite"
version = "0.1.0"
description = "Mono for Story Sprout"
readme = "README.md"
requires-python = ">=3.13"

[tool.uv]
managed = true

[tool.uv.workspace]
members = [
    "services/web",
    "services/docs_server",
    "services/lab",
    "libs/celery-typed",
]

[project.optional-dependencies]
dev = [
    "pre-commit>=4.3.0",
    "ruff>=0.12.9",
]

[tool.ruff]
line-length = 119
fix = true
lint.select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # Pyflakes
    "UP",  # pyupgrade
    "B",   # flake8-bugbear
    "SIM", # flake8-simplify
    "I",   # isort
]
lint.pydocstyle.convention = "google"

[tool.ruff.format]
quote-style = "double"
skip-magic-trailing-comma = false
docstring-code-line-length = 79
