# Generated by Django 5.2.4 on 2025-08-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0009_page_image_draft_page_image_generating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="content",
            field=models.TextField(blank=True, default="", help_text="Content for this page", null=True),
        ),
        migrations.AlterField(
            model_name="page",
            name="image_text",
            field=models.TextField(blank=True, default="", help_text="Image text for this page", null=True),
        ),
    ]
