# Generated by Django 5.2.6 on 2025-09-12 19:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0013_alter_story_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="content_draft",
        ),
        migrations.RemoveField(
            model_name="page",
            name="content_generating",
        ),
        migrations.RemoveField(
            model_name="page",
            name="image_draft",
        ),
        migrations.RemoveField(
            model_name="page",
            name="image_generating",
        ),
        migrations.RemoveField(
            model_name="page",
            name="image_text_draft",
        ),
        migrations.RemoveField(
            model_name="page",
            name="image_text_generating",
        ),
    ]
