# Generated by Django 5.2.4 on 2025-08-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0011_alter_story_description_alter_story_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="description",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
