# Generated by Django 5.2.6 on 2025-09-24 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0015_message_position_autoincrement"),
        ("stories", "0015_remove_story_title_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="conversation",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ai.conversation",
            ),
        ),
    ]
