# Generated by Django 5.2.6 on 2025-09-24 15:43

from django.db import migrations


def create_conversations(apps, schema_editor):
    Story = apps.get_model("stories", "Story")
    Conversation = apps.get_model("ai", "Conversation")

    stories = Story.objects.filter(conversation__isnull=True)
    for story in stories.iterator():
        conversation = Conversation.objects.create(
            user=story.user,
            meta={"story_uuid": str(story.uuid)},
        )
        story.conversation = conversation
        story.save(update_fields=["conversation"])


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0016_story_conversation"),
    ]

    operations = [
        migrations.RunPython(create_conversations, migrations.RunPython.noop),
    ]
