# Generated by Django 5.2.4 on 2025-07-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_alter_page_options_alter_story_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_generating',
            field=models.BooleanField(default=False, help_text='Whether content is being generated for this page'),
        ),
    ]
