# Generated by Django 5.2.4 on 2025-07-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_page_content_generating'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='content_draft',
            field=models.TextField(blank=True, help_text='Draft content stored while generating', null=True),
        ),
    ]
