# Generated by Django 5.2.4 on 2025-08-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0010_alter_page_content_alter_page_image_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.CharField(default="New Story", max_length=50),
        ),
    ]
