# Generated by Django 5.2.4 on 2025-08-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0012_alter_story_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="story",
            name="title",
            field=models.CharField(blank=True, default="New Story", max_length=50, null=True),
        ),
    ]
