# Generated by Django 5.2.4 on 2025-07-15 20:50

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPrompt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("prompt", models.TextField(help_text="The prompt text to send to the AI")),
                (
                    "max_tokens",
                    models.IntegerField(default=100, help_text="Maximum number of tokens for the response"),
                ),
                ("result", models.TextField(blank=True, help_text="The AI-generated result", null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the AI processing",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "processed_at",
                    models.DateTimeField(blank=True, help_text="When the prompt was processed", null=True),
                ),
                ("task_id", models.CharField(blank=True, help_text="Celery task ID", max_length=255, null=True)),
                (
                    "error_message",
                    models.TextField(blank=True, help_text="Error message if the task failed", null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this prompt",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Prompt",
                "verbose_name_plural": "AI Prompts",
                "ordering": ["-created_at"],
            },
        ),
    ]
