# Generated by Django 5.2.4 on 2025-09-03 01:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0006_airequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aiworkflow",
            name="target_ct",
        ),
        migrations.RemoveField(
            model_name="aiworkflow",
            name="user",
        ),
        migrations.RenameField(
            model_name="airequest",
            old_name="workflow_name",
            new_name="workflow",
        ),
        migrations.DeleteModel(
            name="AiJob",
        ),
        migrations.DeleteModel(
            name="AIWorkflow",
        ),
    ]
