# Generated by Django 5.2.4 on 2025-09-03 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0007_remove_aiworkflow_target_ct_remove_aiworkflow_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airequest",
            name="target_uuid",
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
    ]
