# Generated by Django 5.2.6 on 2025-09-16 02:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0011_alter_run_options_remove_run_first_ts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artifacts",
            name="run",
        ),
        migrations.AddField(
            model_name="artifacts",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artifacts",
            name="file",
            field=models.FileField(default=None, upload_to="artifacts"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artifacts",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="artifacts",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("content", models.JSONField()),
                ("position", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="ai.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["conversation", "position"],
                "unique_together": {("conversation", "position")},
            },
        ),
        migrations.DeleteModel(
            name="Run",
        ),
    ]
