# Generated by Django 5.2.6 on 2025-09-16 02:51

import uuid

from django.db import migrations


def generate_unique_uuids(apps, schema_editor):
    """Generate unique UUIDs for existing Artifacts records."""
    Artifacts = apps.get_model("ai", "Artifacts")
    for artifact in Artifacts.objects.all():
        artifact.uuid = uuid.uuid4()
        artifact.save(update_fields=["uuid"])


def reverse_generate_unique_uuids(apps, schema_editor):
    """Reverse operation - no action needed."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0012_remove_artifacts_run_artifacts_created_at_and_more"),
    ]

    operations = [
        migrations.RunPython(generate_unique_uuids, reverse_generate_unique_uuids),
    ]
