# Generated by Django 5.2.4 on 2025-07-16 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aiprompt_model_aiprompt_tokens_used'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('page_text', 'Page Text'), ('page_image', 'Page Image')], help_text='Type of AI job being performed', max_length=20)),
                ('target_id', models.PositiveIntegerField(help_text='ID of the target object')),
                ('template_key', models.CharField(help_text='Key identifying the prompt template to use', max_length=80)),
                ('template_ver', models.CharField(help_text='Template version (git sha / semver)', max_length=40)),
                ('model_name', models.CharField(help_text='AI model to use for generation', max_length=80)),
                ('prompt_payload', models.JSONField(help_text='Rendered context (no secrets)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the AI job', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of processing attempts')),
                ('last_error', models.TextField(blank=True, help_text='Last error message if the job failed')),
                ('output_text', models.TextField(blank=True, help_text='Small result (text jobs)')),
                ('output_ref', models.CharField(blank=True, help_text='S3 key for images / big blobs', max_length=255)),
                ('usage_tokens', models.JSONField(blank=True, help_text='Token usage like {"in":123,"out":456}', null=True)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=4, help_text='Cost of the AI request in USD', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When job processing started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When job processing completed', null=True)),
                ('target_ct', models.ForeignKey(help_text='Content type of the target object', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User who requested this job', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Job',
                'verbose_name_plural': 'AI Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='AIPrompt',
        ),
        migrations.AddIndex(
            model_name='aijob',
            index=models.Index(fields=['status', 'created_at'], name='ai_aijob_status_2512af_idx'),
        ),
        migrations.AddIndex(
            model_name='aijob',
            index=models.Index(fields=['job_type', 'status'], name='ai_aijob_job_typ_9e609c_idx'),
        ),
        migrations.AddIndex(
            model_name='aijob',
            index=models.Index(fields=['target_ct', 'target_id'], name='ai_aijob_target__e81329_idx'),
        ),
    ]
