# Generated by Django 5.2.4 on 2025-07-18 03:35

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0003_aijob_delete_aiprompt_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIWorkflow",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("target_id", models.PositiveIntegerField()),
                ("target_field", models.CharField(max_length=50)),
                ("target_flag", models.CharField(max_length=50)),
                ("workflow_func", models.CharField(max_length=50)),
                ("workflow_payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "AI Workflow",
                "verbose_name_plural": "AI Workflows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="aijob",
            name="ai_aijob_job_typ_9e609c_idx",
        ),
        migrations.RemoveIndex(
            model_name="aijob",
            name="ai_aijob_target__e81329_idx",
        ),
        migrations.RemoveField(
            model_name="aijob",
            name="job_type",
        ),
        migrations.RemoveField(
            model_name="aijob",
            name="model_name",
        ),
        migrations.RemoveField(
            model_name="aijob",
            name="output_ref",
        ),
        migrations.RemoveField(
            model_name="aijob",
            name="output_text",
        ),
        migrations.RemoveField(
            model_name="aijob",
            name="target_ct",
        ),
        migrations.RemoveField(
            model_name="aijob",
            name="target_id",
        ),
        migrations.RemoveField(
            model_name="aijob",
            name="template_key",
        ),
        migrations.RemoveField(
            model_name="aijob",
            name="template_ver",
        ),
        migrations.RemoveField(
            model_name="aijob",
            name="user",
        ),
        migrations.AddField(
            model_name="aijob",
            name="prompt_result",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="aiworkflow",
            name="target_ct",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
        ),
        migrations.AddField(
            model_name="aiworkflow",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="aijob",
            name="workflow",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="ai.aiworkflow"),
        ),
        migrations.AddIndex(
            model_name="aijob",
            index=models.Index(fields=["workflow", "status"], name="ai_aijob_workflo_c6e26f_idx"),
        ),
    ]
